### ISSUE TITLE
Adding option to select debug image

### ISSUE THREAD

**Issue by debMan** [pashevskii/debug-pods-lens-extension#5]
Hello dear @pashevskii
In order to troubleshoot networking problems, we usually need an image contains networking tools. 
I think it will be better if the option to select the debug image be available or let the user chooses debug image from a drop-down menu containing several images.
For the drop-down menu, I suggest adding `praqma/network-multitool` image.

Best regards.

**Comment by pashevskii** [comment]
Hi, thanks for your ideas, 
please try this build https://github.com/pashevskii/debug-pods-lens-extension/releases/download/0.1.1/lens-debug-tools-0.1.1.tgz
I've added an option in lens preferences that enables listing all debug images in pods menu. 
"praqma/network-multitool" was also added into the default list

**Comment by debMan** [comment]
WoW. That's cool.
I liked t contribute to your repo, but unfortunately, I do not have enough JS and TS knowledge. 
That's cool. Thanks a lot.

**Comment by pashevskii** [comment]
Thank you for your ideas on how to improve the project
