### ISSUE TITLE
Invalid escaping sequence when running on Windows Powershell

### ISSUE THREAD

**Issue by nroypf** [pashevskii/debug-pods-lens-extension#6]
Starting the debug pod fail and report the error
> error: Invalid JSON Patch

Lens is launching the command through Powershell and isn't escaping the overrides Json script properly.  The double quotes should be escape with a backslash ('\')

What it does:

```powershelll
kubectl run myapp-1-debug -n myns -it --image=busybox --restart=Never  --attach  --overrides='{ "spec": { "nodeName": "aks-myapppool01-15895598-vmss000001" } }' --labels=createdBy=lens-debug-extension --rm
```

What it should do:

```powershelll
kubectl run myapp-1-debug -n myns -it --image=busybox --restart=Never  --attach  --overrides='{ \"spec": { \"nodeName\": \"aks-myapppool01-15895598-vmss000001\" } }' --labels=createdBy=lens-debug-extension --rm
```

**Comment by pashevskii** [comment]
Hi!
Thank you for the issue. 
Please, try https://github.com/pashevskii/debug-pods-lens-extension/releases/download/0.1.2/lens-debug-tools-0.1.2.tgz
